[WIP] [output] Elasticsearch output plugin
moiot/gravity pull request #130
Opened 2019-04-06 13:35 UTC by ScienJus

Implementation for #127 .

After code review and running a case in the real world, I will add the document.😿

2019-04-09 07:39 UTC, Ryan-Git commented
LGTM

2019-04-10 17:09 UTC, ming535 requested changes

2019-04-10 17:09 UTC, ming535 commented on pkg/outputs/elasticsearch/elasticsearch.go
> +			continue
If this plugin does not support source table without primary key, we should return error with detailed information here, and tell the user that we do not support it in the error message. The scheduler will panic and stop the process.

2019-04-10 17:09 UTC, ming-relax commented on pkg/outputs/elasticsearch/elasticsearch.go
> +				time.Sleep(5 * time.Second)
The scheduler will retry if `Execute` returns error in `batch_table_scheduler.go`

2019-04-10 17:09 UTC, ming-relax commented on pkg/outputs/elasticsearch/elasticsearch.go
> +			} else if output.config.IgnoreBadRequest {
can we combine the first three `if` cases together?

2019-04-10 17:09 UTC, ming-relax commented on pkg/outputs/elasticsearch/elasticsearch.go
> +				// TODO do we need a metcris in prometheus for this?
may be we can just reuse `OutputCounter `

2019-04-10 17:09 UTC, ming-relax commented on pkg/outputs/elasticsearch/elasticsearch.go
> +				log.Panicf("[output_elasticsearch] Received an error from server, status: [%d], index: %s, details: %s.", result.Status, result.Index, marshalError(result.Error))
we can just return the error to scheduler with detailed error information. The scheduler will panic if multiple retries failed.

2019-04-11 05:58 UTC, ScienJus commented
@ming-relax Thanks, please take a look again.

2019-04-11 15:17 UTC, ming-relax commented
@ScienJus Let's add the document into this PR

2019-04-14 15:20 UTC, ming535 approved these changes

2019-04-14 15:21 UTC, merged