add table name based on target table in manual sql engine
moiot/gravity pull request #15
Opened 2019-01-03 09:36 UTC by ming-relax

2019-01-03 10:09 UTC, Ryan-Git requested changes
would it be better to use go-template to build the statement?

2019-01-03 15:03 UTC, ming-relax commented
@Ryan-Git the sql template is built using text/template now, but still keep the sql arg to use the default context of `Msg.DmlMsg.Data`

2019-01-04 02:39 UTC, Ryan-Git approved these changes

2019-01-04 02:43 UTC, Ryan-Git commented
> @Ryan-Git the sql template is built using text/template now, but still keep the sql arg to use the default context of `Msg.DmlMsg.Data`

it's ok. otherwise we have to take parameter serialization into account. 
Now it looks good to me.

2019-01-04 02:53 UTC, merged