feat: support create & alter table
moiot/gravity pull request #23
Opened 2019-01-07 13:55 UTC by Ryan-Git

2019-01-07 15:03 UTC, ming535 requested changes

2019-01-07 15:03 UTC, ming535 commented on gravity/emitter/emitter.go
> +	gen, ok := e.sequenceGenerators[inputStreamKey]
`gen` maybe `nil` and will cause panic

2019-01-07 15:03 UTC, ming535 commented on gravity/inputs/mysqlstream/binlog_tailer.go
> +				if dbName == config2.GravityDBName || dbName == "mysql" {
we also need to check if the dbName equals to `drc` and make sure it is backward compatible.

2019-01-07 15:03 UTC, ming535 commented on gravity/inputs/mysqlstream/binlog_tailer.go
> -	close(msg.Done)
How can we wait for this `Done` channel if we do not close it here?

2019-01-07 15:03 UTC, ming535 commented on gravity/inputs/mysqlstream/utils.go
> +func extractSchemaNameFromDDLQueryEvent(p *parser.Parser, ev *replication.QueryEvent) (db, table string, node ast.StmtNode) {
Can you add a test case here to test the case that when schema name is not included in the QueryEvent ?

2019-01-07 15:03 UTC, ming535 commented on gravity/outputs/mysql/mysql.go
> +		switch msg.Type {
can you add some test cases here?

2019-01-08 02:12 UTC, Ryan-Git commented on gravity/emitter/emitter.go
> +	gen, ok := e.sequenceGenerators[inputStreamKey]
why?

2019-01-08 02:12 UTC, Ryan-Git commented on gravity/inputs/mysqlstream/binlog_tailer.go
> +				if dbName == config2.GravityDBName || dbName == "mysql" {
I'll update this after #24 is merged

2019-01-08 02:14 UTC, Ryan-Git commented on gravity/inputs/mysqlstream/binlog_tailer.go
> -	close(msg.Done)
It's closed in `acker`. Otherwise every callback should close it, which is easy to be forgotten (and it is forgotten in many places now).

2019-01-08 02:15 UTC, Ryan-Git commented on gravity/inputs/mysqlstream/utils.go
> +func extractSchemaNameFromDDLQueryEvent(p *parser.Parser, ev *replication.QueryEvent) (db, table string, node ast.StmtNode) {
there is an `add user` ddl in integration test.

2019-01-08 02:16 UTC, Ryan-Git commented on gravity/outputs/mysql/mysql.go
> +		switch msg.Type {
create table, alter table, add user and their undos have already been added in generator.

2019-01-08 02:17 UTC, Ryan-Git commented on gravity/emitter/emitter.go
> +	gen, ok := e.sequenceGenerators[inputStreamKey]
why? if it's nil, ok should be false

2019-01-08 05:48 UTC, Ryan-Git commented on gravity/inputs/mysqlstream/binlog_tailer.go
> +				if dbName == config2.GravityDBName || dbName == "mysql" {
done

2019-01-08 07:11 UTC, ming535 approved these changes

2019-01-08 08:52 UTC, merged