fix bidirectional drop
moiot/gravity pull request #230
Opened 2019-11-13 12:00 UTC by Ryan-Git

this fixes #225

2019-11-14 03:36 UTC, CrazyNash commented on pkg/outputs/mysql/mysql.go
> +				if output.hasDropped(msg.Database, msg.Table) {
这里应该是 ！output.hasDropped(msg.Database, msg.Table)？

2019-11-14 10:31 UTC, Ryan-Git commented on pkg/outputs/mysql/mysql.go
> +				if output.hasDropped(msg.Database, msg.Table) {
对-。-

2019-11-20 11:49 UTC, CrazyNash commented
这个PR什么时候能release出来？

2019-11-20 14:00 UTC, Ryan-Git commented
@ming-relax PTAL

2019-11-21 01:15 UTC, ming535 requested changes

2019-11-21 01:15 UTC, ming535 commented on pkg/outputs/mysql/mysql.go
> +					log.Debugf("table %s has been dropped recently. This might be a bidirectional stmt, ignore", utils.TableIdentity(msg.Database, msg.Table))
`Debug` --> `Info` or `Warn` ?

2019-11-21 01:15 UTC, ming-relax commented on pkg/outputs/mysql/mysql.go
> +		if now.Sub(value.(time.Time)) > keepDropTableSeconds {
`now.Sub(value.(time.Time))` --> `now.Sub(value.(time.Time))).Seconds()` ?

2019-11-21 02:29 UTC, Ryan-Git commented on pkg/outputs/mysql/mysql.go
> +					log.Debugf("table %s has been dropped recently. This might be a bidirectional stmt, ignore", utils.TableIdentity(msg.Database, msg.Table))
ok

2019-11-21 02:55 UTC, ming535 approved these changes

2019-11-21 02:56 UTC, merged