Mongo batch
moiot/gravity pull request #78
Opened 2019-01-31 08:40 UTC by Ryan-Git

2019-02-26 08:49 UTC, Ryan-Git commented
@ming-relax PTAL

2019-02-26 09:09 UTC, ming535 requested changes

2019-02-26 09:09 UTC, ming535 commented on pkg/mongo/mongo.go
> +	err := session.DB(db).C(collection).Find(nil).Select(bson.M{"_id": 1}).Limit(1).One(&t)
'_id' in mongo might not start with `1`, it might not be the value generated by mongod. How about use `db.collection.find({}).count() `? https://docs.mongodb.com/manual/reference/method/db.collection.count/

2019-02-26 09:09 UTC, ming535 commented on pkg/inputs/mongobatch/input.go
> +	posLock  sync.Mutex
better to put the logic related to postiion to position_value.go

2019-02-26 09:09 UTC, ming535 commented on pkg/inputs/mongobatch/input.go
> +	}
better to put the logic related to postiion to position_value.go

2019-02-26 09:44 UTC, Ryan-Git commented on pkg/mongo/mongo.go
> +	err := session.DB(db).C(collection).Find(nil).Select(bson.M{"_id": 1}).Limit(1).One(&t)
already use `find({})`. 1 meaning just return the id column.

2019-02-26 09:47 UTC, Ryan-Git commented on pkg/inputs/mongobatch/input.go
> +	posLock  sync.Mutex
put all these fields as package level variable?

2019-02-27 10:27 UTC, ming535 approved these changes

2019-02-27 11:01 UTC, merged